## Character '#' is used for one line comment in properties file

#Organization
org=Rays Technologies

#Generic error messages
error.require={0} is required
error.integer={0} must be an integer
error.date={0} is invalid date
error.email={0} is invalid Email ID
error.marks.max=Marks can not be greater than 100
 
#Database connection Parameters
url=jdbc:mysql://localhost:3306/p04
driver=com.mysql.cj.jdbc.Driver
username=root
password=root
DATABASE=JDBC
service=javaBean
acquireIncrement=1
initialPoolSize=1
maxPoolSize=5
minPoolSize=1
timeout=10


#Email Server Parameters
smtp.server=smtp.gmail.com
smtp.port=465
email.login=webmaster@sunrays.co.in
email.pwd=PA$$1234
checkinterval=


#Pagination
page.size=10